name: plugin-docker-compose

services:
  plugin-keycloak:
    container_name: plugin-docker-compose-plugin-keycloak
    depends_on:
      - plugin-keycloak-database
    image: quay.io/keycloak/keycloak:26.2.2
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://plugin-keycloak-database/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    volumes:
      - ./imports/keycloak:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
      - --http-enabled=true
      - --hostname-strict=false
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() == 200 ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth' ]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 5s

  plugin-keycloak-database:
    image: postgres:17.4
    container_name: plugin-docker-compose-plugin-keycloak-database
    ports:
      - "54329:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  plugin-database:
    container_name: plugin-docker-compose-plugin-database
    image: postgres:17.4
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: plugin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plugin
    volumes:
      - plugin-database-data:/var/lib/postgres # persist data even if container shuts down

  plugin-rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: plugin-docker-compose-plugin-rabbitmq
    volumes:
      - ./imports/plugin-rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./imports/plugin-rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
    command: >
      bash -c "
        rabbitmq-plugins enable --offline rabbitmq_stream rabbitmq_stream_management &&
        rabbitmq-server
      "

  #ZGW

  openzaak-redis:
    image: redis:8.2.2
    container_name: plugin-docker-compose-openzaak-redis
    expose:
      - 6379

  openzaak-db:
    image: postgis/postgis:17-3.4
    container_name: plugin-docker-compose-openzaak-db
    platform: linux/amd64
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=openzaak
      - POSTGRES_PASSWORD=openzaak
      - POSTGRES_DB=openzaak

  openzaak:
    image: openzaak/open-zaak:1.25.0
    container_name: plugin-docker-compose-openzaak
    platform: linux/amd64
    environment: &openzaak-env
      - DB_HOST=openzaak-db
      - DB_POST=5432
      - SECRET_KEY=veryRestrictedSecretKey
      - DB_USER=openzaak
      - DB_PASSWORD=openzaak
      - DB_NAME=openzaak
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,host.docker.internal,172.17.0.1,openzaak
      - OPENZAAK_SUPERUSER_USERNAME=admin
      - OPENZAAK_SUPERUSER_EMAIL=admin@admin.org
      - DJANGO_SUPERUSER_PASSWORD=admin
      - SENDFILE_BACKEND=django_sendfile.backends.simple
      - NOTIFICATIONS_DISABLED=true
      - CACHE_DEFAULT=openzaak-redis:6379/0
      - CACHE_AXES=openzaak-redis:6379/0
      - CELERY_BROKER_URL=redis://openzaak-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://openzaak-redis:6379/0
      - REDIS_URL=redis://openzaak-redis:6379/0
      - DISABLE_2FA=True
    ports:
      - "8001:8000"
    depends_on:
      - openzaak-db
      - openzaak-redis
    volumes:
      - openzaak-private-media:/app/private-media
      - ./imports/open-zaak/dump_demodata.sh:/app/dump_demodata.sh
      - ./imports/open-zaak/fixtures:/app/demodata
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; exit(requests.head('http://localhost:8000/admin/').status_code not in [200, 302])" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  openzaak-celery:
    image: openzaak/open-zaak:1.25.0
    container_name: plugin-docker-compose-openzaak-celery
    platform: linux/amd64
    environment: *openzaak-env
    command: /celery_worker.sh
    healthcheck:
      test: [ "CMD", "python", "/app/bin/check_celery_worker_liveness.py" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  openzaak-import:
    image: openzaak/open-zaak:1.25.0
    container_name: plugin-docker-compose-openzaak-import
    platform: linux/amd64
    environment: *openzaak-env
    command: sh /app/load_demodata.sh
    volumes:
      - ./imports/open-zaak/fixtures:/app/demodata
      - ./imports/open-zaak/load_demodata.sh:/app/load_demodata.sh
    depends_on:
      openzaak:
        condition: service_healthy

volumes:
  plugin-database-data:
  openzaak-private-media:
